# Generated by Django 2.2.1 on 2019-05-20 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_task_complete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='slug',
            new_name='list',
        ),
        migrations.RemoveField(
            model_name='list',
            name='name',
        ),
    ]
