# Generated by Django 2.2.1 on 2019-05-20 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20190520_1602'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='list',
            new_name='slug',
        ),
        migrations.AddField(
            model_name='list',
            name='name',
            field=models.CharField(default='a', max_length=100),
            preserve_default=False,
        ),
    ]
