# Generated by Django 2.2.1 on 2019-05-20 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_auto_20190520_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='name',
        ),
    ]
